apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-rest-deployment
  labels:
    app: spring-rest-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-rest-app
  template:
    metadata:
      labels:
        app: spring-rest-app
    spec:
      containers:
        - name: app
          image: laminba2003/spring-rest:1.2
          env:
            - name: MODE
              value: demo