apiVersion: v1
kind: Service
metadata:
  name: spring-rest-service
  labels:
    app: spring-rest-service
spec:
  selector:
    app: spring-rest-app
  ports:
    - name: http
      port: 9093
      targetPort: 9090
  type: LoadBalancer