apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - image: elasticsearch:7.8.0
        imagePullPolicy: IfNotPresent
        name: elasticsearch
        resources: 
         requests:
          cpu: "500m"
          memory: "512M"
         limits:
          cpu: "500m"
          memory: "1Gi"
        env:
         - name: discovery.type
           value: single-node
         - name: esJavaOpts
           value: "-Xmx512m -Xms512m"