apiVersion: v1
kind: Service
metadata:
  name: spring-rest
  labels:
    app: spring-rest
spec:
  selector:
    app: spring-rest
  ports:
    - name: http
      port: 9093
      targetPort: 9090
  type: LoadBalancer