apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-training
data: 
  management.metrics.export.wavefront.uri: https://wavefront.surf
  spring.datasource.url: jdbc:mysql://mysql:3306/spring_training?enabledTLSProtocols=TLSv1.2
  spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:8083/auth/realms/example
  spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://localhost:8083/auth/realms/example/protocol/openid-connect/certs
  management.health.probes.enabled: "true"

