apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-elasticsearch
data:
  fluentd.conf: |

    # Ignore fluentd own events
    <match fluent.**>
      @type null
    </match>
    
    <match kubernetes.var.log.containers.**kube-system**.log>
      @type null
    </match>

    # <match kubernetes.var.log.containers.**kube-logging**.log>
    # @type null
    # </match>

    <match kubernetes.var.log.containers.**_istio-proxy_**>
      @type null
    </match>
    

    # TCP input to receive logs from the forwarders
    <source>
      @type forward
      bind 0.0.0.0
      port 24224
    </source>

    # HTTP input for the liveness and readiness probes
    <source>
      @type http
      bind 0.0.0.0
      port 9880
    </source>

    # Throw the healthcheck to the standard output instead of forwarding it
    <match fluentd.healthcheck>
      @type stdout
    </match>
    
    <match kubernetes.**>
     @type rewrite_tag_filter
     <rule>
       key log
       pattern /^\{.+\}$/
       tag json.${tag}
     </rule>
     <rule>
       key log
       pattern /^\{.+\}$/
       tag nonejson.${tag}
       invert true
     </rule>
    </match>

    
    <filter json.**>
      @type parser
      key_name log
      reserve_data true
      <parse>
        @type json
      </parse>
    </filter>
  
    # Send the json logs to elasticsearch
    <match json.**>
      @type elasticsearch
      include_tag_key true
      host elasticsearch.default.svc.cluster.local
      port 9200
      logstash_format true

      <buffer>
        @type file
        path /opt/bitnami/fluentd/logs/buffers/logs.buffer
        flush_thread_count 2
        flush_interval 5s
      </buffer>
    </match>