apiVersion: v1
kind: Service
metadata:
  name: spring-microservices
  labels:
    app: spring-microservices
spec:
  selector:
    app: spring-microservices
  ports:
    - name: http
      port: 9093
      targetPort: 8089
  type: LoadBalancer